CREATE TABLE adress (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR2(100) NOT NULL,
    street VARCHAR2(100) NOT NULL
);

CREATE TABLE clients (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    phone_number VARCHAR2(20) NOT NULL,
    adress_id NUMBER,
    CONSTRAINT fk_clients_adress FOREIGN KEY (adress_id) REFERENCES adress(id)
);

CREATE TABLE driver (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    phone_number VARCHAR2(20) NOT NULL
);

CREATE TABLE restaurant (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    adress_id NUMBER,
    CONSTRAINT fk_restaurant_adress FOREIGN KEY (adress_id) REFERENCES adress(id)
);


CREATE TABLE menu_item (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    price NUMBER(8,2) NOT NULL,
    description VARCHAR2(255),
    restaurant_id NUMBER,
    CONSTRAINT fk_menu_item_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant(id)
);

CREATE TABLE orders (
    id VARCHAR2(20) PRIMARY KEY,
    client_id NUMBER,
    CONSTRAINT fk_orders_client FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE payment (
    id VARCHAR2(20) PRIMARY KEY,
    amount NUMBER(8,2) NOT NULL,
    method VARCHAR2(50),
    payment_time TIMESTAMP,
    order_id VARCHAR2(20),
    CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE delivery (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR2(20),
    driver_id NUMBER,
    delivery_time TIMESTAMP,
    status VARCHAR2(50),
    CONSTRAINT fk_delivery_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_delivery_driver FOREIGN KEY (driver_id) REFERENCES driver(id)
);


INSERT INTO adress (city, street) VALUES ('Cluj', 'X');
INSERT INTO adress (city, street) VALUES ('Bucuresti', 'Y');

INSERT INTO clients (name, last_name, phone_number, adress_id)
VALUES ('Ion', 'Popescu', '0722333444', 1);

INSERT INTO clients (name, last_name, phone_number, adress_id)
VALUES ('Maria', 'Ionescu', '0733444555', 2);

INSERT INTO driver (name, last_name, phone_number)
VALUES ('Alex', 'Georgescu', '0744555666');

INSERT INTO driver (name, last_name, phone_number)
VALUES ('Elena', 'Dumitrescu', '0722666777');

INSERT INTO restaurant (name, adress_id)
VALUES ('La Bunica', 1);

INSERT INTO restaurant (name, adress_id)
VALUES ('PizzaFix', 2);

INSERT INTO menu_item (name, price, description, restaurant_id)
VALUES ('Pizza Margherita', 25.00, 'Pizza simpla ', 1);

INSERT INTO menu_item (name, price, description, restaurant_id)
VALUES ('Burger Vita', 30.00, 'Burger cu vita', 2);

INSERT INTO orders (id, client_id)
VALUES ('ORD001', 3);

INSERT INTO orders (id, client_id)
VALUES ('ORD002', 4);

INSERT INTO payment (id, amount, method, payment_time, order_id)
VALUES ('PAY001', 55.00, 'Card', SYSTIMESTAMP, 'ORD001');

INSERT INTO payment (id, amount, method, payment_time, order_id)
VALUES ('PAY002', 30.00, 'Cash', SYSTIMESTAMP, 'ORD002');

INSERT INTO delivery (order_id, driver_id, delivery_time, status)
VALUES ('ORD001', 1, SYSTIMESTAMP + INTERVAL '40' MINUTE, 'livrata');

INSERT INTO delivery (order_id, driver_id, delivery_time, status)
VALUES ('ORD002', 2, SYSTIMESTAMP + INTERVAL '30' MINUTE, 'in tranzit');

SELECT * FROM clients;
SELECT * FROM driver;
SELECT * FROM restaurant;
SELECT * FROM orders;